TRUNCATE TABLE request_trial_links CASCADE;
TRUNCATE TABLE requests CASCADE;
TRUNCATE TABLE data_access CASCADE;
TRUNCATE TABLE design CASCADE;
TRUNCATE TABLE outcomes CASCADE;
TRUNCATE TABLE sponsors CASCADE;
TRUNCATE TABLE investigator CASCADE;
TRUNCATE TABLE institution CASCADE;
TRUNCATE TABLE eligibility_criteria CASCADE;

-- Main tables
TRUNCATE TABLE clinical_trials CASCADE;
TRUNCATE TABLE platforms CASCADE;
